// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frgblvloxhcnwrgvjazk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZ2JsdmxveGhjbndyZ3ZqYXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTY4MzcsImV4cCI6MjA2NDY5MjgzN30.zFOY8tmkFhu-bfm1GiiU6aNwn4Fo1ZETxLMCa7HdM1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);